---

- name: Update apt cache and upgrade system
  apt:
    update_cache: yes
    upgrade: dist
  become: true

- name: Gather disk usage and system facts
  setup:
    gather_subset:
      - hardware
      - network
      - virtual
      - distribution
      - mounts
      - loadavg

- name: Check services status
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop: "{{ services_to_check }}"
  register: services_check
  ignore_errors: true

- name: Build list of service states
  set_fact:
    services_status: "{{ services_check.results | map(attribute='item') | zip(services_check.results | map(attribute='status')) | list }}"


- name: Render system health report
  template:
    src: system_health_report.j2
    dest: "{{ log_file_path }}"
    mode: '0644'
